### ISSUE TITLE
Incorrect import in company.reducer.spec

### ISSUE THREAD

**Issue by Magrangs** [duncanhunter/ngrx-play-by-play#1]
The file company.reducer.spec.ts incorrectly imports 'reducer' from company.reducer. It should import 'companyReducer'.

(Great course btw).

**Comment by duncanhunter** [comment]
Hi

Thanks for the taking the time to point this out and I am excited to hear you like the course!

I have fixed the incorrect reference :)

Thanks

**Comment by Magrangs** [comment]
@duncanhunter Is there any chance you could expand the example a bit especially the company-edit-component where it gets the selected company (fromRoot.getSelectedCompany) and then the whole process for updating the store? I am struggling to find a simple example and the platform example on ngrx with the entities just seems too complex. Many thanks.

**Comment by duncanhunter** [comment]
Hi

Thanks for the suggestion. I am proposing a new ngrx course to go through this all in detail. Feel free to message me on twitter "@dunchunter" with a little more detail of what you want to do and see if I can help.
